server:
  port: 9002
  
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/shopping?characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
  redis:
    database: 0
    host: 47.94.155.74
    port: 6379
    password: Qinfo20180507
    jedis:
      pool:
        max-active: 1
        max-wait: -1
        max-idle: 10
        min-idle: 2
    timeout: 1000
    
  rabbitmq:
    host: 121.199.16.83
    port: 5672
    username: zhanghaodong1
    password: 961006
